[package]
name = "brainf-ck-rs"
description = "A brainfuck interpreter with a visualizer."
version = "0.1.2"
authors = ["valflrt"]
repository = "https://github.com/valflrt/brainf-ck-rs"
license = "MIT"
edition = "2021"

[dependencies]
colored = "3.0.0"
